export const EXTENSION_UPDATE = "EXTENSION_UPDATE";
export const ADDRESS_UPDATE = "ADDRESS_UPDATE";

export const BALANCE_LOADING = "BALANCE_LOADING";
export const BALANCE_UPDATE = "BALANCE_UPDATE";
export const BALANCE_FAIL = "BALANCE_FAIL";

export const RECEIVE_DATA_LOADING = "RECEIVE_DATA_LOADING";
export const RECEIVE_DATA_UPDATE = "RECEIVE_DATA_UPDATE";
export const RECEIVE_DATA_FAIL = "RECEIVE_DATA_FAIL";

export const STREAM_DATA_LOADING = "STREAM_DATA_LOADING";
export const STREAM_DATA_UPDATE = "STREAM_DATA_UPDATE";
export const STREAM_DATA_FAIL = "STREAM_DATA_FAIL";
export const SET_SOCKET = "SET_SOCKET";

export const NEW_SOCKET_STREAM = "NEW_SOCKET_STREAM";
export const UPDATE_SOCKET_STREAM = "UPDATE_SOCKET_STREAM";
export const WITHDRAW_SOCKET_STREAM = "WITHDRAW_SOCKET_STREAM";
export const CANCEL_SOCKET_STREAM = "CANCEL_SOCKET_STREAM";

export const STREAM_WITHDRAWN_UPDATE = "STREAM_WITHDRAWN_UPDATE";

export const HISTORY_DETAILS_LOADING = "HISTORY_DETAILS_LOADING";
export const HISTORY_DETAILS_SUCCESS = "HISTORY_DETAILS_SUCCESS";
export const HISTORY_DETAILS_FAIL = "HISTORY_DETAILS_FAIL";

export const NEW_STREAM_COLOR = "NEW_STREAM_COLOR";
export const CANCEL_STREAM_COLOR = "CANCEL_STREAM_COLOR";
export const WITHDRAW_STREAM_COLOR = "WITHDRAW_STREAM_COLOR";

export const UPDATE_CONTRACT_FEE = "UPDATE_CONTRACT_FEE";

export const UPDATE_USER_IDENTIFIER = "UPDATE_USER_IDENTIFIER";
export const UPDATE_USER_IDENTIFIER_ADDRESS = "UPDATE_USER_IDENTIFIER_ADDRESS";

export const EDIT_SHOW_NICKNAMES = "EDIT_SHOW_NICKNAMES";
