export const daiAddress = "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
export const daiAbi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "spender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
        ],
        name: "Approval",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "userAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address payable",
                name: "relayerAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "functionSignature",
                type: "bytes",
            },
        ],
        name: "MetaTransactionExecuted",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {indexed: true, internalType: "bytes32", name: "role", type: "bytes32"},
            {
                indexed: true,
                internalType: "bytes32",
                name: "previousAdminRole",
                type: "bytes32",
            },
            {
                indexed: true,
                internalType: "bytes32",
                name: "newAdminRole",
                type: "bytes32",
            },
        ],
        name: "RoleAdminChanged",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {indexed: true, internalType: "bytes32", name: "role", type: "bytes32"},
            {
                indexed: true,
                internalType: "address",
                name: "account",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
        ],
        name: "RoleGranted",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {indexed: true, internalType: "bytes32", name: "role", type: "bytes32"},
            {
                indexed: true,
                internalType: "address",
                name: "account",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
        ],
        name: "RoleRevoked",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {indexed: true, internalType: "address", name: "from", type: "address"},
            {indexed: true, internalType: "address", name: "to", type: "address"},
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
        ],
        name: "Transfer",
        type: "event",
    },
    {
        inputs: [],
        name: "CHILD_CHAIN_ID",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "CHILD_CHAIN_ID_BYTES",
        outputs: [{internalType: "bytes", name: "", type: "bytes"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "DEFAULT_ADMIN_ROLE",
        outputs: [{internalType: "bytes32", name: "", type: "bytes32"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "DEPOSITOR_ROLE",
        outputs: [{internalType: "bytes32", name: "", type: "bytes32"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "ERC712_VERSION",
        outputs: [{internalType: "string", name: "", type: "string"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "PERMIT_TYPEHASH",
        outputs: [{internalType: "bytes32", name: "", type: "bytes32"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "ROOT_CHAIN_ID",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "ROOT_CHAIN_ID_BYTES",
        outputs: [{internalType: "bytes", name: "", type: "bytes"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "owner", type: "address"},
            {internalType: "address", name: "spender", type: "address"},
        ],
        name: "allowance",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "spender", type: "address"},
            {internalType: "uint256", name: "amount", type: "uint256"},
        ],
        name: "approve",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "address", name: "account", type: "address"}],
        name: "balanceOf",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "string", name: "name_", type: "string"}],
        name: "changeName",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "decimals",
        outputs: [{internalType: "uint8", name: "", type: "uint8"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "spender", type: "address"},
            {internalType: "uint256", name: "subtractedValue", type: "uint256"},
        ],
        name: "decreaseAllowance",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "user", type: "address"},
            {internalType: "bytes", name: "depositData", type: "bytes"},
        ],
        name: "deposit",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "userAddress", type: "address"},
            {internalType: "bytes", name: "functionSignature", type: "bytes"},
            {internalType: "bytes32", name: "sigR", type: "bytes32"},
            {internalType: "bytes32", name: "sigS", type: "bytes32"},
            {internalType: "uint8", name: "sigV", type: "uint8"},
        ],
        name: "executeMetaTransaction",
        outputs: [{internalType: "bytes", name: "", type: "bytes"}],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "getChainId",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [],
        name: "getDomainSeperator",
        outputs: [{internalType: "bytes32", name: "", type: "bytes32"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "address", name: "user", type: "address"}],
        name: "getNonce",
        outputs: [{internalType: "uint256", name: "nonce", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "bytes32", name: "role", type: "bytes32"}],
        name: "getRoleAdmin",
        outputs: [{internalType: "bytes32", name: "", type: "bytes32"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "bytes32", name: "role", type: "bytes32"},
            {internalType: "uint256", name: "index", type: "uint256"},
        ],
        name: "getRoleMember",
        outputs: [{internalType: "address", name: "", type: "address"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "bytes32", name: "role", type: "bytes32"}],
        name: "getRoleMemberCount",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "bytes32", name: "role", type: "bytes32"},
            {internalType: "address", name: "account", type: "address"},
        ],
        name: "grantRole",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "bytes32", name: "role", type: "bytes32"},
            {internalType: "address", name: "account", type: "address"},
        ],
        name: "hasRole",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "spender", type: "address"},
            {internalType: "uint256", name: "addedValue", type: "uint256"},
        ],
        name: "increaseAllowance",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "string", name: "name_", type: "string"},
            {internalType: "string", name: "symbol_", type: "string"},
            {internalType: "uint8", name: "decimals_", type: "uint8"},
            {internalType: "address", name: "childChainManager", type: "address"},
        ],
        name: "initialize",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "src", type: "address"},
            {internalType: "address", name: "dst", type: "address"},
            {internalType: "uint256", name: "wad", type: "uint256"},
        ],
        name: "move",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "name",
        outputs: [{internalType: "string", name: "", type: "string"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "holder", type: "address"},
            {internalType: "address", name: "spender", type: "address"},
            {internalType: "uint256", name: "nonce", type: "uint256"},
            {internalType: "uint256", name: "expiry", type: "uint256"},
            {internalType: "bool", name: "allowed", type: "bool"},
            {internalType: "uint8", name: "v", type: "uint8"},
            {internalType: "bytes32", name: "r", type: "bytes32"},
            {internalType: "bytes32", name: "s", type: "bytes32"},
        ],
        name: "permit",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "usr", type: "address"},
            {internalType: "uint256", name: "wad", type: "uint256"},
        ],
        name: "pull",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "usr", type: "address"},
            {internalType: "uint256", name: "wad", type: "uint256"},
        ],
        name: "push",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "bytes32", name: "role", type: "bytes32"},
            {internalType: "address", name: "account", type: "address"},
        ],
        name: "renounceRole",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "bytes32", name: "role", type: "bytes32"},
            {internalType: "address", name: "account", type: "address"},
        ],
        name: "revokeRole",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "symbol",
        outputs: [{internalType: "string", name: "", type: "string"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalSupply",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "recipient", type: "address"},
            {internalType: "uint256", name: "amount", type: "uint256"},
        ],
        name: "transfer",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "sender", type: "address"},
            {internalType: "address", name: "recipient", type: "address"},
            {internalType: "uint256", name: "amount", type: "uint256"},
        ],
        name: "transferFrom",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "amount", type: "uint256"}],
        name: "withdraw",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
]

export const contractAddress = "0x0F964e5FD9976A7A1FC974aA559b7C9ef2E1C1Df"
export const contractABI = [
    {inputs: [], stateMutability: "nonpayable", type: "constructor"},
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "streamId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "recipient",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "senderBalance",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "recipientBalance",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "cancelTime",
                type: "uint256",
            },
        ],
        name: "CancelStream",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "streamId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "recipient",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "deposit",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "tokenAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "startTime",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "stopTime",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "blockTime",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bool",
                name: "senderCancel",
                type: "bool",
            },
            {
                indexed: false,
                internalType: "bool",
                name: "recipientCancel",
                type: "bool",
            },
        ],
        name: "CreateStream",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "previousOwner",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "account",
                type: "address",
            },
        ],
        name: "Paused",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "streamId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "recipient",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "clientAmount",
                type: "uint256",
            },
        ],
        name: "TranferRecipientFromCancelStream",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "streamId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "senderBalance",
                type: "uint256",
            },
        ],
        name: "TranferSenderFromCancelStream",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "account",
                type: "address",
            },
        ],
        name: "Unpaused",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "streamId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "recipient",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "WithdrawFromStream",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "companyAccount",
                type: "address",
            },
        ],
        name: "newCompanyAccount",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "newFee",
                type: "uint256",
            },
        ],
        name: "newFee",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "address",
                name: "reciver",
                type: "address",
            },
        ],
        name: "remFromContract",
        type: "event",
    },
    {
        inputs: [{internalType: "address", name: "", type: "address"}],
        name: "accept",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "address", name: "_token", type: "address"}],
        name: "addNewToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "uint256", name: "streamId", type: "uint256"},
            {internalType: "address", name: "who", type: "address"},
        ],
        name: "balanceOf",
        outputs: [{internalType: "uint256", name: "balance", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "streamId", type: "uint256"}],
        name: "cancelStream",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "_fee", type: "uint256"}],
        name: "changeFee",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "contractBalance",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "recipient", type: "address"},
            {internalType: "uint256", name: "deposit", type: "uint256"},
            {internalType: "address", name: "tokenAddress", type: "address"},
            {internalType: "uint256", name: "startTime", type: "uint256"},
            {internalType: "uint256", name: "stopTime", type: "uint256"},
            {internalType: "uint256", name: "blockTime", type: "uint256"},
            {internalType: "bool", name: "senderCancel", type: "bool"},
            {internalType: "bool", name: "recipientCancel", type: "bool"},
        ],
        name: "createStream",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "streamId", type: "uint256"}],
        name: "exist",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "fee",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getBalanceOfThisContract",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "streamId", type: "uint256"}],
        name: "getStream",
        outputs: [
            {internalType: "address", name: "sender", type: "address"},
            {internalType: "address", name: "recipient", type: "address"},
            {internalType: "uint256", name: "deposit", type: "uint256"},
            {internalType: "address", name: "tokenAddress", type: "address"},
            {internalType: "uint256", name: "startTime", type: "uint256"},
            {internalType: "uint256", name: "stopTime", type: "uint256"},
            {internalType: "uint256", name: "remainingBalance", type: "uint256"},
            {internalType: "uint256", name: "ratePerSecond", type: "uint256"},
            {internalType: "uint256", name: "senderRemainder", type: "uint256"},
            {internalType: "uint256", name: "blockTime", type: "uint256"},
            {internalType: "bool", name: "senderCancel", type: "bool"},
            {internalType: "bool", name: "recipientCancel", type: "bool"},
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "nextStreamId",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{internalType: "address", name: "", type: "address"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "paused",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "address", name: "_token", type: "address"}],
        name: "removeToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "address", name: "newOwner", type: "address"}],
        name: "transferOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "address", name: "_tokenAddress", type: "address"},
            {internalType: "uint256", name: "_amount", type: "uint256"},
            {internalType: "address", name: "_reciver", type: "address"},
        ],
        name: "withdrawForHolders",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "uint256", name: "streamId", type: "uint256"},
            {internalType: "uint256", name: "amount", type: "uint256"},
        ],
        name: "withdrawFromStream",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "nonpayable",
        type: "function",
    },
]

export const nicknameContractAddress = "0x2adFB66eDDDeeb81Dfb8f38C5e3bfA0b73a47Ea1"
export const nicknameContractABI = [
    {
        "inputs": [{"internalType": "address", "name": "", "type": "address"}],
        "name": "addrNick",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{"internalType": "string", "name": "_nickOld", "type": "string"}, {
            "internalType": "string",
            "name": "_nickNew",
            "type": "string"
        }], "name": "changeNick", "outputs": [], "stateMutability": "nonpayable", "type": "function"
    }, {
        "inputs": [{"internalType": "string", "name": "", "type": "string"}],
        "name": "nickAddr",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{"internalType": "string", "name": "_nick", "type": "string"}],
        "name": "setNick",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }]
