import Head from "next/head";
import React from "react";
import Header from "../components/Header";
import st from '../styles/mainPage.module.scss'
import {Carousel} from '../components/carousel-compound/Carousel'
import {Page} from '../components/carousel-compound/Page/Page'
import {Image} from "react-bootstrap";
import Link from "next/link";
import {StartStreamSymbol} from "../components/icons/StartStream";

const cases = [
    {id: 1, name: 'Simple payment'},
    {id: 2, name: 'Family Allowance'},
    {id: 3, name: 'Parking or rent transport'},
    {id: 4, name: 'Subscriptions'},
    {id: 5, name: 'Company RSU\'s'},
    {id: 6, name: 'Pension Plan Payments'},
    {id: 7, name: 'Rent Payments'},
    {id: 8, name: 'Donation'},
    {id: 9, name: 'Inheritance'},
]

export default function Home() {
    return (
        <>
            <Head>
                <title>ctrlX</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header active=""/>
            <div className={st.main__wrapper}>
                <div className={st.left}>
                    <div className={st.left__wrapper}>
                        <h1 className={st.gradient__heading}>
                            New streaming
                            <br/>
                            payment system
                        </h1>
                        <div className={st.app__main_text}>
                            CtrlX is an easy & secure money streaming protocol available on the blockchain network.
                            CtrlX
                            protocol allows per-second transactions between ctrlX users.
                        </div>
                        <div className={st.use__cases}>
                            <h2>Use Cases:</h2>
                            <div className={st.app__main_container}>
                                <Carousel infinite>
                                    {cases.map(item =>
                                        <Page key={item.id}>
                                            <Link href="/streams">
                                                <div className={st.item}>{item.name}</div>
                                            </Link>
                                        </Page>
                                    )}
                                </Carousel>
                            </div>
                        </div>
                        <div>
                            <Link href="/streams">
                                <div
                                    className={st.navbar_app__button}
                                >
                                    <div className={st.main_btn}>Start</div>
                                    <StartStreamSymbol width={16} height={16} fill='#fff'/>
                                </div>
                            </Link>
                            <div className={st.market_wrap}>
                                <Link href='http://appstore.ru/'>
                                    <a target="_blank">
                                        <Image src="/images/appstore.png" className={st.marketItem} alt="appstore"/>
                                    </a>
                                </Link>
                                <Link href='https://play.google.com/'>
                                    <a target="_blank">
                                        <Image src="/images/googleplay.png" className={st.marketItem} alt="appstore"/>
                                    </a>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={st.img__wrap}>
                    <div className={st.img__wrapper}>
                        <Image src="/images/phoneLaptop.png" className={st.img} alt="logo"/>
                    </div>
                </div>
            </div>
        </>
    )
}
