import Head from "next/head";
import { useState, useEffect } from "react";

import { Container, Row, Col, Button, Navbar } from "react-bootstrap";

import Header from "../components/Header";

import GettingStartedManual from "../components/userManual/GettingStarted";
import StreamsManual from "../components/userManual/StreamsManual";
import CompoundingStreamsManual from "../components/userManual/CompoundingStreamsManual";

const Faq = () => {
  const [active, setActive] = useState("gettingStarted");
  const [scroll, setScroll] = useState(false);

  useEffect(() => {
    window.addEventListener("scroll", (e) => {
      setScroll(window.pageYOffset > 30);
    });
  }, []);

  return (
    <>
      <Head>
        <title>ctrlX | User Manual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${scroll ? "sticky-navbar" : ""}`}>
          <Header active="user manual" />
      </div>
      {scroll && <div className="sticky-navbar-style" />}
      <Container className="max-container px-2 mb-lg-2">
        <Row className="mt-3">
          <Col lg={4}>
            <h1 className="my-3 gradient-heading">User Manual</h1>
            <Navbar sticky="top" style={{ top: "60px" }}>
              <div className="user-manual-controller px-3 w-100 mt-3">
                <ul className="py-3 px-0">
                  <li>
                    <Button
                      variant="transparnet"
                      className={active !== "gettingStarted" ? "inactive" : ""}
                      onClick={() => {
                        setActive("gettingStarted");
                        window.scrollTo(0, 0);
                      }}
                    >
                      Getting started
                    </Button>
                  </li>
                  <li>
                    <Button
                      variant="transparnet"
                      className={active !== "streams" ? "inactive" : ""}
                      onClick={() => {
                        setActive("streams");
                        window.scrollTo(0, 0);
                      }}
                    >
                      Streams
                    </Button>
                  </li>
                  {/* <li>
                    <Button
                      variant="transparnet"
                      className={
                        active !== "compoundingStreams" ? "inactive" : ""
                      }
                      onClick={() => {
                        setActive("compoundingStreams");
                        window.scrollTo(0, 0);
                      }}
                    >
                      Compounding Streams
                    </Button>
                  </li> */}
                </ul>
              </div>
            </Navbar>
          </Col>
          <Col lg={8} className="py-3">
            <div className="user-manual-article">
              {active === "gettingStarted" ? (
                <GettingStartedManual />
              ) : active === "streams" ? (
                <StreamsManual />
              ) : // : active === "compoundingStreams" ? (
              //   <CompoundingStreamsManual />
              // )
              null}
            </div>
          </Col>
        </Row>
      </Container>
    </>
  );
};

export default Faq;
